### ISSUE TITLE
Style Sheet Needed

### ISSUE THREAD

**Issue by dykstranet** [consensusRealityIO/RSBP#1]
CSS design help needed. This page needs to look good on all devices. It is often used on a phone or tablet and although usable, it is not great. Often the QR code is initially displayed off screen and scrolling is necessary.

Also the CSS needs to be flexible enough so that the page can be integrated into the look and feel of any branded website.

**Comment by Frankenmint** [comment]
$350 in BTC and I'll have it fixed in the next 5 days.  We can use escrow on Bitcointalk or I could use satoshibox with prior screenshots of your site w/ my css mods on diff devices as proof before payment.

**Comment by dykstranet** [comment]
This problem was fixed with 1 line of code which was donated by Niels Lange. Thank you Niels!

That line of code was:

`<meta name="viewport" content="width=device-width, initial-scale=1">`
