### ISSUE TITLE
Intelligent TRX Fee Detection - Detect "Replace by Fee" and Low-Fee transactions

### ISSUE THREAD

**Issue by dykstranet** [consensusRealityIO/RSBP#12]
With release [12.X](https://github.com/bitcoin/bitcoin/releases/tag/v0.12.0) of the bitcoin core client, Replace by Fee (RBF) has been implemented. 

This presents a potential problem for Merchants because a customer could pay by bitcoin, take delivery of goods, and cancel/revert funds back to themselves.

RSBP needs to detect the presence of a RBF and low fee transactions and warn the merchant that it is necessary to wait for 1 confirmation before releasing goods. 

RBF Links:
https://bitcointalk.org/index.php?topic=199947.0

**Comment by simonhorlick** [comment]
There are already some free APIs online that mark whether transactions have opt-in-rbf enabled. See this one for instance: https://www.blockcypher.com/dev/bitcoin/#tx

The RSBP code could call out to that and decide whether to display a message?

**Comment by dykstranet** [comment]
`opt_in_rbf bool    Optional Returns true if this transaction has opted in to Replace-By-Fee (RBF), either true or not present. You can read more about Opt-In RBF here.`

**Comment by dykstranet** [comment]
For this kind of API call, would be good to have a second source of information; a second, distinct, independent API provider of the very same information.

**Comment by dykstranet** [comment]
This issues was resolved by @infertux
